version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "PowerDialer"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-vzq93rs0pz2y"
s3_prefix = "PowerDialer"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
